"""Discover DS18B20 probes and generate stable, named ESPHome entities."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys
import threading
import time
import urllib.request
from collections.abc import Callable, Iterable


DS18B20_LOG_PATTERN = re.compile(r"\b0x([0-9A-Fa-f]{16})\s+\(DS18B20\)")


def parse_ds18b20_addresses(lines: Iterable[str]) -> list[int]:
    """Return unique DS18B20 ROM IDs from native ESPHome scan output."""
    addresses = {
        address
        for line in lines
        for match in DS18B20_LOG_PATTERN.finditer(line)
        if (address := int(match.group(1), 16)) & 0xFF == 0x28
    }
    return sorted(addresses)


def load_names(path: pathlib.Path) -> dict[int, str]:
    """Load and validate the persistent ROM-ID-to-name registry."""
    if not path.exists():
        return {}
    raw_names = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw_names, dict):
        raise ValueError(f"{path} must contain a JSON object")

    names: dict[int, str] = {}
    for raw_address, raw_name in raw_names.items():
        if not isinstance(raw_address, str) or not re.fullmatch(
            r"0x[0-9A-Fa-f]{16}", raw_address
        ):
            raise ValueError(f"Invalid 1-Wire ROM ID in {path}: {raw_address!r}")
        address = int(raw_address, 16)
        if address & 0xFF != 0x28:
            raise ValueError(f"ROM ID is not a DS18B20 in {path}: {raw_address}")
        if not isinstance(raw_name, str) or not raw_name.strip():
            raise ValueError(f"Missing speaking name for {raw_address} in {path}")
        names[address] = raw_name.strip()
    return names


def assign_missing_names(
    addresses: Iterable[int],
    names: dict[int, str],
    input_func: Callable[[str], str],
) -> dict[int, str]:
    """Prompt once for each newly discovered physical probe."""
    updated = dict(names)
    for address in sorted(set(addresses)):
        if address in updated:
            continue
        address_text = f"0x{address:016X}"
        entered = input_func(f"Speaking name for {address_text}: ").strip()
        updated[address] = entered or f"1-Wire {address_text}"
    return updated


def render_names_json(names: dict[int, str]) -> str:
    serialized = {f"0x{address:016X}": names[address] for address in sorted(names)}
    return json.dumps(serialized, ensure_ascii=False, indent=2) + "\n"


def render_sensor_yaml(addresses: Iterable[int], names: dict[int, str]) -> str:
    """Render a deterministic, address-bound ESPHome sensor-list include."""
    unique_addresses = sorted(set(addresses))
    lines = [
        "# Generated by tools/diagnostics/discover_one_wire.py.",
        "# Names are bound to immutable ROM IDs in 1-wire-sensor-names.json.",
    ]
    if not unique_addresses:
        lines.append("[]")
        return "\n".join(lines) + "\n"

    for sorting_weight, address in enumerate(unique_addresses, start=1):
        address_text = f"0x{address:016X}"
        entity_name = json.dumps(
            f"${{device_name}} {names[address]}", ensure_ascii=False
        )
        lines.extend(
            [
                "- platform: dallas_temp",
                "  one_wire_id: temperature_bus",
                f"  address: {address_text}",
                f"  name: {entity_name}",
                "  resolution: 12",
                "  update_interval: 60s",
                "  filters:",
                "    - filter_out: 85.0",
                "    - lambda: |-",
                "        if (x < -55.0f || x > 125.0f) return NAN;",
                "        return x;",
                "    - timeout: 180s",
                "  web_server:",
                "    sorting_group_id: sg_one_wire",
                f"    sorting_weight: {sorting_weight}",
            ]
        )
    return "\n".join(lines) + "\n"


def write_if_changed(path: pathlib.Path, content: str) -> bool:
    """Atomically replace path when its UTF-8 content changed."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    temporary_path = path.with_suffix(path.suffix + ".tmp")
    temporary_path.write_text(content, encoding="utf-8", newline="\n")
    temporary_path.replace(path)
    return True


def copy_output(process: subprocess.Popen[str], lines: list[str]) -> None:
    assert process.stdout is not None
    for line in process.stdout:
        sys.stdout.write(line)
        lines.append(line)


def capture_live_logs(host: str, config: pathlib.Path, duration: int) -> list[str]:
    """Capture the native DS2484 scan across a controlled device restart."""
    process = subprocess.Popen(
        ["esphome", "logs", str(config), "--device", host],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    lines: list[str] = []
    reader = threading.Thread(target=copy_output, args=(process, lines), daemon=True)
    reader.start()

    try:
        time.sleep(5)
        restart_url = f"http://{host}/button/esphome_hems_restart/press"
        request = urllib.request.Request(restart_url, method="POST", data=b"")
        with urllib.request.urlopen(request, timeout=10) as response:
            print(f"Restart requested: HTTP {response.status}")
        time.sleep(duration)
    finally:
        process.terminate()
        try:
            process.wait(timeout=10)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=5)
        reader.join(timeout=5)
    return lines


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Discover, name and register native DS2484 temperature probes."
    )
    parser.add_argument("--host", default="192.168.178.24")
    parser.add_argument("--config", default="esphome-hems.yaml")
    parser.add_argument("--duration", type=int, default=25)
    parser.add_argument("--input", type=pathlib.Path, help="Parse an existing log instead")
    parser.add_argument("--output", type=pathlib.Path, default=pathlib.Path("1-wire-sensors.yaml"))
    parser.add_argument(
        "--names", type=pathlib.Path, default=pathlib.Path("1-wire-sensor-names.json")
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="Use ROM-based names for new probes instead of prompting",
    )
    return parser.parse_args()


def resolve_path(repository_root: pathlib.Path, path: pathlib.Path | str) -> pathlib.Path:
    candidate = pathlib.Path(path)
    return candidate if candidate.is_absolute() else repository_root / candidate


def main() -> int:
    args = parse_args()
    repository_root = pathlib.Path(__file__).resolve().parents[2]
    config = resolve_path(repository_root, args.config)
    output = resolve_path(repository_root, args.output)
    names_path = resolve_path(repository_root, args.names)

    if args.input is not None:
        input_path = resolve_path(repository_root, args.input)
        lines = input_path.read_text(encoding="utf-8", errors="replace").splitlines()
    else:
        lines = capture_live_logs(args.host, config, args.duration)

    addresses = parse_ds18b20_addresses(lines)
    if not addresses:
        print("No valid DS18B20 devices found; registration was not changed.", file=sys.stderr)
        return 1

    names = load_names(names_path)
    missing_addresses = [address for address in addresses if address not in names]
    if missing_addresses and not args.non_interactive and not sys.stdin.isatty():
        print(
            "New probes need speaking names, but no interactive terminal is available. "
            "Run interactively or pass --non-interactive for ROM-based names.",
            file=sys.stderr,
        )
        return 2
    input_func = (lambda prompt: "") if args.non_interactive else input
    names = assign_missing_names(addresses, names, input_func)

    names_changed = write_if_changed(names_path, render_names_json(names))
    sensors_changed = write_if_changed(output, render_sensor_yaml(names.keys(), names))
    for address in addresses:
        print(f"0x{address:016X}: {names[address]}")
    status = "updated" if names_changed or sensors_changed else "unchanged"
    print(
        f"Registration {status}: {len(addresses)} discovered, "
        f"{len(names)} registered DS18B20 sensor(s)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())